### ISSUE TITLE
Exception when trying to add/remove files to/from F# Azure Functions projects

### ISSUE THREAD

**Issue by mikebattista** [ionide/Forge#127]
**Describe the bug**
I receive the below error in Forge's output in VS Code when trying to add/remove files from a new Azure Functions app created with the Azure Functions extension:

*C:\Users\<USER>\.vscode\extensions\ionide.ionide-fsharp-4.0.6\bin_forge\Forge.dll add file -n c:\Users\<USER>\Desktop\MyFunctionApp\MyHttpTrigger.fs --no-prompt
Unhandled error:
Object reference not set to an instance of an object.*

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the Azure Functions VS Code extension
2. Set "azureFunctions.projectLanguage": "F#" in your *USER* settings
3. Run "Azure Functions: Create New Project"
4. Change the template filter to "All" to unlock F# templates
5. Select HttpTrigger and then the default for the rest of the options
6. Currently the .fs file for the HttpTrigger is not included in the fsproj by default (debatable whether that's a feature or a bug) so to add it, open the file, then run "F#: Add Current File to Project"
7. Observe the error above in the Output window with Forge selected

**Expected behaviour**
HttpTriggerFSharp.fs is added to the fsproj file

**Environment (please complete the following information):**
 - OS: Windows 10 1903
 - Ionide version: 4.0.6
 - VSCode version: 1.36.1 (user setup)
 - dotnet SDK version: 3.0.100-preview6-012264
 - mono / .Net Framework version: N/A

**Additional context**
Testing against F# console apps created with Forge in VS Code and with dotnet new worked fine so the problem seemed unique to the Azure Functions template.

I downloaded the latest Forge source to debug and get more context on the nullref exception and believe the issue is with the additional items the Azure Functions templates add to the fsproj, namely:

``
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
``

If I remove this ItemGroup, everything works as expected.

I think I tracked it down to the code [here](https://github.com/ionide/Forge/blob/8ca36c419db2fa746188ddb6fb467356ac6caaee/src/Forge.ProjectSystem/ProjectSystem.fs#L384) which accepts "None" elements as SourceFiles and assumes/expects they have an "Include" attribute which these don't (it doesn't use the try* pattern as subsequent lines do). This cascades later into the below NullReferenceException when trying to get the value of the "Include" attribute which doesn't exist here.

**The fix is to remove the assumption that all SourceFile elements in an fsproj have an "Include" attribute or change the definition of what a SourceFile-compatible fsproj element is based on how the Azure Functions templates work.**

``
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Forge.XLinq.XAttr.value(XAttribute xattr) in C:\Users\<USER>\Desktop\Forge\src\Forge.ProjectSystem\XLinq.fs:line 127
   at Forge.XLinq.XElem.getAttributeValue[a](String name, a xelem) in C:\Users\<USER>\Desktop\Forge\src\Forge.ProjectSystem\XLinq.fs:line 187
   at Forge.ProjectSystem.SourceFile.fromXElem(XElement xelem) in C:\Users\<USER>\Desktop\Forge\src\Forge.ProjectSystem\ProjectSystem.fs:line 383
   at Forge.ProjectSystem.srcTree@1118.Invoke(XElement arg00) in C:\Users\<USER>\Desktop\Forge\src\Forge.ProjectSystem\ProjectSystem.fs:line 1118
   at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr)
   at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Forge.ProjectSystem.FsProject.fromXDoc(XDocument xdoc) in C:\Users\<USER>\Desktop\Forge\src\Forge.ProjectSystem\ProjectSystem.fs:line 1113
   at Forge.ProjectManager.Furnace.loadFsProject(String projectPath) in C:\Users\<USER>\Desktop\Forge\src\Forge.Core\ProjectManager.fs:line 59
   at Forge.Commands.addFile@559-1.Invoke(String _arg1) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 573
   at Forge.Commands.addFile@558.Invoke(Unit unitVar) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 558
   at Forge.Prelude.MaybeBuilder.Delay[T](FSharpFunc`2 f) in C:\Users\<USER>\Desktop\Forge\src\Forge.ProjectSystem\Prelude.fs:line 217
   at Forge.Commands.addFile(ParseResults`1 results) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 557
   at Forge.Commands.processAdd@622-1.Invoke(ParseResults`1 results) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 622
   at Forge.Commands.execCommand[a,b](FSharpFunc`2 fn, String[] args) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 491
   at Forge.Commands.processAdd(String[] args) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 622
   at Forge.Commands.check@915-2.Invoke(String[] args) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 915
   at Forge.Commands.check@908.Invoke(ParseResults`1 res) in c:\Users\<USER>\Desktop\Forge\src\Forge\Commands.fs:line 924}
``

**Comment by deyanp** [comment]
Great investigation, was googling for the same error on an Azure Functions F# project, and found this post. I can confirm that removing the None Update items is a workaround, however better to preserve those items ...


```
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
    <None Update="proxies.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
```

**Comment by deyanp** [comment]
Found a workaround - change Update to Include

See also https://github.com/Azure/Azure-Functions/issues/1177
